# Generated by Django 4.0.4 on 2022-05-14 21:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_name', models.CharField(default='add first name', max_length=30)),
                ('sem', models.IntegerField(choices=[(1, '1 SEM'), (2, '2 SEM'), (3, '3 SEM'), (4, '4 SEM'), (5, '5 SEM'), (6, '1 SEM'), (7, '1 SEM'), (8, '1 SEM')], default='MALE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('usn', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('avatars', models.ImageField(default='default_student.jpg', upload_to='')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 2, 41, 6, 934184))),
                ('date_of_jpining', models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 2, 41, 6, 934184))),
                ('email', models.EmailField(default='email', max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('GAY', 'GAY')], default='MALE', max_length=10)),
                ('branch', models.CharField(choices=[(1, 'E & C'), (2, 'MECHANICAL'), (3, 'COMPUTER SCIENCE')], max_length=30)),
                ('division', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('GAY', 'GAY')], max_length=30)),
                ('sem', models.IntegerField(choices=[(1, '1 SEM'), (2, '2 SEM'), (3, '3 SEM'), (4, '4 SEM'), (5, '5 SEM'), (6, '1 SEM'), (7, '1 SEM'), (8, '1 SEM')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
