# Generated by Django 4.0.4 on 2022-05-14 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 2, 41, 55, 962253)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_jpining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 2, 41, 55, 962253)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='sem',
            field=models.IntegerField(choices=[(1, '1 SEM'), (2, '2 SEM'), (3, '3 SEM'), (4, '4 SEM'), (5, '5 SEM'), (6, '1 SEM'), (7, '1 SEM'), (8, '1 SEM')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sem',
            field=models.IntegerField(choices=[(1, '1 SEM'), (2, '2 SEM'), (3, '3 SEM'), (4, '4 SEM'), (5, '5 SEM'), (6, '1 SEM'), (7, '1 SEM'), (8, '1 SEM')]),
        ),
    ]
