# Generated by Django 4.0.4 on 2022-05-14 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_faculty_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 2, 43, 34, 439856)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_jpining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 2, 43, 34, 439856)),
        ),
    ]
