# Generated by Django 4.0.4 on 2022-05-14 21:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_faculty_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='usn',
            new_name='fid',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='division',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='sem',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='avatars',
            field=models.ImageField(default='default_faculty.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='branch',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('GAY', 'GAY')], max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 3, 13, 5, 198966)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_jpining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 3, 13, 5, 198966)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('GAY', 'GAY')], default='MALE', max_length=30),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usn', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('avatars', models.ImageField(default='default_student.jpg', upload_to='')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 3, 13, 5, 199991))),
                ('date_of_jpining', models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 3, 13, 5, 199991))),
                ('email', models.EmailField(default='email', max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('GAY', 'GAY')], default='MALE', max_length=10)),
                ('branch', models.CharField(choices=[(1, 'E & C'), (2, 'MECHANICAL'), (3, 'COMPUTER SCIENCE')], max_length=30)),
                ('division', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('GAY', 'GAY')], max_length=30)),
                ('sem', models.IntegerField(choices=[(1, '1 SEM'), (2, '2 SEM'), (3, '3 SEM'), (4, '4 SEM'), (5, '5 SEM'), (6, '1 SEM'), (7, '1 SEM'), (8, '1 SEM')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
