# Generated by Django 4.0.4 on 2022-05-14 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_usn_faculty_fid_remove_faculty_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='date_of_jpining',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_jpining',
        ),
        migrations.AddField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 3, 13, 58, 922407)),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 3, 13, 58, 924403)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 3, 13, 58, 922407)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 3, 13, 58, 924403)),
        ),
    ]
