# Generated by Django 4.0.4 on 2022-05-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_faculty_date_of_jpining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
