# Generated by Django 4.0.4 on 2022-05-15 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_faculty_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='avatars',
            field=models.ImageField(default='default_faculty.jpg', upload_to='faculties/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 16, 0, 22, 31, 432798)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 16, 0, 22, 31, 432798)),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatars',
            field=models.ImageField(default='default_student.jpg', upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 16, 0, 22, 31, 433821)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 16, 0, 22, 31, 433821)),
        ),
    ]
