# Generated by Django 4.0.4 on 2022-05-15 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_faculty_avatars_alter_faculty_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='password',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='branch',
            field=models.CharField(choices=[('E & C', 'E & C'), ('MECHANICAL', 'MECHANICAL'), ('COMPUTER SCIENCE', 'COMPUTER SCIENCE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 16, 1, 6, 4, 371334)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 16, 1, 6, 4, 371334)),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('E & C', 'E & C'), ('MECHANICAL', 'MECHANICAL'), ('COMPUTER SCIENCE', 'COMPUTER SCIENCE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 16, 1, 6, 4, 371334)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 16, 1, 6, 4, 371334)),
        ),
    ]
