# Generated by Django 4.0.4 on 2022-05-29 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_student_student_usn_alter_faculty_avatars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_usn', models.CharField(max_length=30, unique=True)),
                ('status', models.BooleanField()),
                ('branch', models.CharField(choices=[('E & C', 'E & C'), ('MECHANICAL', 'MECHANICAL'), ('COMPUTER SCIENCE', 'COMPUTER SCIENCE')], max_length=30)),
                ('division', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=30)),
                ('subject', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('GAY', 'GAY')], max_length=30)),
                ('sem', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='status',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 29, 7, 29, 28, 824755)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 29, 7, 29, 28, 824755)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 29, 7, 29, 28, 824755)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 29, 7, 29, 28, 824755)),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_usn',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
